server:
  port: 8080

spring:
  application:
    name: config-center-server

  datasource:
    url: jdbc:h2:mem:configdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

#拉低后测试 code：4290，请求过于频繁，请稍后再试
#同时查metric指标上升
rate-limit:
  enabled: true
  capacity: 5
  refill-per-second: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] traceId=%X{traceId} %logger{36} - %msg%n"