spring:
  datasource:
    url: ${CONFIG_CENTER_DB_URL}
    username: ${CONFIG_CENTER_DB_USERNAME}
    password: ${CONFIG_CENTER_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  h2:
    console:
      enabled: false

security:
  api-keys:
    - key: ${CONFIG_CENTER_API_KEY}
      app: demo-app
      env: dev
